version: "3.9"

services:
  backend:
    build: ./backend
    container_name: examynex-backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - backend_data:/app/exam.db

  frontend:
    build: ./frontend
    container_name: examynex-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  backend_data:
